spring:
  rabbitmq:
    host: ${mq.host}
    port: 5672
    username: ${mq.username}
    password: ${mq.password}
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual #开启手动ACK
        prefetch: 5
        default-requeue-rejected: true
        retry:
          max-attempts: 1 #最大重试次数
          enabled: true
          max-interval: 1000000   # 重试最大间隔时间
          initial-interval: 20000  # 重试初始间隔时间
          multiplier: 2 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
